const wellKnownTouristDestinations = [
  "Swiss Alps, Switzerland",
  "Banff National Park, Canada",
  "Mount Everest, Nepal",
  "Zermatt, Switzerland",
  "Rocky Mountains, USA/Canada",
  "Torres del Paine, Chile",
  "Matterhorn, Switzerland/Italy",
  "Aoraki / Mount Cook, New Zealand",
  "Mount Kilimanjaro, Tanzania",
  "Lake Baikal, Russia",
  "Canadian Rockies, Canada",
  "Himalayas, India/Nepal/Tibet",
  "Niseko, Japan",
  "Patagonia, Argentina/Chile",
  "Jungfrau Region, Switzerland",
  "Lofoten Islands, Norway",
  "Dolomites, Italy",
  "Glen Etive, Scotland",
  "Mount Fuji, Japan",
  "Andes Mountains, South America",
  "Denali National Park, USA",
  "Fjord Norway, Norway",
  "Mont Blanc, France/Italy",
  "Saint Elias Mountains, Alaska",
  "Picos de Europa, Spain",
  "Sierra Nevada Mountains, USA",
  "Vail, Colorado, USA",
  "Icelandic Highlands, Iceland",
  "Tian Shan Mountains, Kyrgyzstan/China",
  "Whistler, Canada",
  "Glacier National Park, USA",
  "Mount Rainier, USA",
  "Chamonix-Mont-Blanc, France",
  "Jasper National Park, Canada",
  "Eiger Mountain, Switzerland",
  "Antarctic Peninsula, Antarctica",
  "Mount Etna, Italy",
  "Mönch and Jungfrau, Switzerland",
  "Arctic Circle, Norway/Finland",
  "Tatra Mountains, Poland/Slovakia",
  "Whistler, Canada",
  "North Cascades, USA",
  "Alaska Range, USA",
  "Grand Tetons, USA",
  "Aoraki / Mount Cook National Park, New Zealand",
  "Mount Vesuvius, Italy",
  "Zion National Park, USA",
  "Kilimanjaro National Park, Tanzania"
];
